# Send builds to container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
language: ruby
cache:
- bundler
script: bundle exec rake

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - ruby-head

gemfile:
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
  include:
  - rvm: 1.9
    gemfile: gemfiles/rails_4_0.gemfile
  - rvm: 2.0
    gemfile: gemfiles/rails_4_0.gemfile
  - rvm: 2.1.10
    gemfile: gemfiles/rails_4_0.gemfile
  - rvm: 1.9
    gemfile: gemfiles/rails_4_1.gemfile
  - rvm: 2.0
    gemfile: gemfiles/rails_4_1.gemfile
  - rvm: 2.1.10
    gemfile: gemfiles/rails_4_1.gemfile
  - rvm: 2.2.7
    gemfile: gemfiles/rails_4_1.gemfile
  - rvm: 2.3.4
    gemfile: gemfiles/rails_4_1.gemfile
  - rvm: 2.4.1
    gemfile: gemfiles/rails_4_1.gemfile
  - rvm: 2.4.10
    gemfile: gemfiles/rails_4_1.gemfile
